"""The git plugin's CLI: ``worktree``/``clone`` inspection and cleanup.

These commands only ever manipulate the git-specific `worktree`/`clone`
strategies, so they are the plugin's own business, mounted under ``issuebot
git`` by :func:`issuebot.plugins.mount_cli`.
"""

from __future__ import annotations

import re

import typer

from issuebot import plugins
from issuebot.config import Connection, conn_setting, global_settings, require_config
from issuebot.plugins.workspaces.git import inventory as workspaces
from issuebot.plugins.workspaces.git.settings import GlobalSettings

app = typer.Typer(help="Manage the git workspace plugin's worktrees and clones.")


def _branch_matches_ref(branch: str, ref: str) -> bool:
    """True when ``branch``'s leaf names task ``ref`` — itself, or one of its
    numbered re-cut siblings (``ref-2``, ``ref-3``, ...).

    A re-cut branch's worktree directory (and so `Cut.ref`) is named for the
    branch, not the task ref (`workspace_path_for_branch`), so matching a
    user-typed ref against `Cut.ref` misses every re-cut sibling. Matching
    branch names generated by `branch_candidates` fixed that once, but it has
    two edges of its own: it stops at `MAX_BRANCH_ATTEMPTS`, so a fallback
    branch past that bound is not among the candidates it generates, and it
    reads the connection's *current* `branch_prefix` — a worktree cut under a
    prefix since changed would never match a candidate built from the new one.

    Matching the branch's own leaf against the ref is both unbounded and
    prefix-independent: whatever the prefix was when the branch was cut, only
    the text after the last ``/`` is compared. ``ref`` is escaped because it
    is a task ref, not a regex — it can contain characters (like this
    pattern's own ``-``) that would otherwise be read as one.
    """
    leaf = branch.rsplit("/", 1)[-1]
    return re.fullmatch(rf"{re.escape(ref)}(-\d+)?", leaf) is not None


worktree_app = typer.Typer(
    help="Inspect and clean up issuebot-managed git worktrees.",
    no_args_is_help=True,
)
app.add_typer(worktree_app, name="worktree")

clone_app = typer.Typer(
    help="Inspect and clean up issuebot-managed per-task clones.",
    no_args_is_help=True,
)
app.add_typer(clone_app, name="clone")


def _connections() -> tuple[list[Connection], GlobalSettings]:
    """Every configured connection, and the `[git]` global settings.

    Through the same :func:`~issuebot.config.require_config` every other command
    group uses, so a missing or broken config is the one sentence the user is
    used to rather than this command's own wording — or a traceback.

    This plugin names itself to the registry to fetch its own table — core
    carries no `git_settings` accessor, so a `RunnerContext` builds without
    this plugin installed."""
    cfg = require_config()
    return cfg.connections, global_settings(cfg, plugins.get("workspaces", "git"))


@worktree_app.command("list")
def worktree_list() -> None:
    """List the issuebot-managed worktrees across all configured connections."""
    connections, git = _connections()
    for p in connections:
        if conn_setting(p, "git_init", None) != "worktree":
            continue
        for wt in workspaces.list_worktrees(
            p, worktree_root=git.worktree_root, clone_root=git.clone_root
        ):
            flags = []
            if wt.dirty:
                flags.append("dirty")
            if wt.unpushed:
                flags.append("unpushed")
            suffix = f"  [{', '.join(flags)}]" if flags else ""
            # `wt.ref` is the worktree *directory* name, which for a re-cut
            # branch is the branch leaf ("PAR-12-2"), not the task ref
            # ("PAR-12") — printing it under a column a user reads as "ref"
            # would be a label that lies about a re-cut worktree. `wt.branch`
            # is always accurate and names both the task and the attempt.
            typer.echo(f"{wt.project}  {wt.branch}  {wt.path}{suffix}")


@worktree_app.command("prune")
def worktree_prune(
    refs: list[str] = typer.Argument(None, help="Task refs whose worktrees to remove."),
    all_: bool = typer.Option(False, "--all", help="Remove all managed worktrees."),
    merged: bool = typer.Option(False, "--merged", help="Only remove merged branches."),
    force: bool = typer.Option(False, "--force", help="Remove even if dirty/unpushed."),
) -> None:
    """Remove issuebot-managed worktrees. Requires a selector (refs, --all, or
    --merged). Refuses dirty or unpushed worktrees unless --force."""
    if not refs and not all_ and not merged:
        typer.echo("Specify a selector: task refs, --all, or --merged.", err=True)
        raise typer.Exit(1)

    connections, git = _connections()
    wanted = set(refs or [])
    removed = 0
    for p in connections:
        if conn_setting(p, "git_init", None) != "worktree":
            continue
        # The repo the worktrees belong to: the connection's folder, or the
        # shared clone for a connection whose working copy is cloned.
        source = workspaces.source_repo_folder(p, git.clone_root)
        for wt in workspaces.list_worktrees(
            p, worktree_root=git.worktree_root, clone_root=git.clone_root
        ):
            # `wt.ref` is a branch leaf for a re-cut branch, not the task ref
            # the user typed — see `_branch_matches_ref`. Matched on `wt.branch`.
            if refs and not any(_branch_matches_ref(wt.branch, r) for r in wanted):
                continue
            if merged and not workspaces.is_merged(source, wt.branch):
                continue
            if not force and (wt.dirty or wt.unpushed):
                typer.echo(f"skip {wt.branch}: dirty/unpushed (use --force).", err=True)
                continue
            ok = workspaces.remove(wt, project_folder=source, force=force)
            if ok:
                removed += 1
            typer.echo(f"{'removed' if ok else 'failed'} {wt.branch} ({wt.path})")
    if removed == 0:
        typer.echo("No matching worktrees to prune.")


@clone_app.command("list")
def clone_list() -> None:
    """List the issuebot-managed clones across all configured connections."""
    connections, git = _connections()
    for p in connections:
        # Clones belong to connections whose working copy IS a clone, which
        # is what `repo` says — not to a strategy value any more.
        if not conn_setting(p, "repo"):
            continue
        for c in workspaces.list_clones(p, clone_root=git.clone_root):
            flags = []
            if c.dirty:
                flags.append("dirty")
            if c.unpushed:
                flags.append("unpushed")
            suffix = f"  [{', '.join(flags)}]" if flags else ""
            typer.echo(f"{c.project}  {c.ref}  {c.branch}  {c.path}{suffix}")


@clone_app.command("prune")
def clone_prune(
    refs: list[str] = typer.Argument(None, help="Task refs whose clones to remove."),
    all_: bool = typer.Option(False, "--all", help="Remove all managed clones."),
    merged: bool = typer.Option(False, "--merged", help="Only remove merged PRs."),
    force: bool = typer.Option(False, "--force", help="Remove even if dirty/unpushed."),
) -> None:
    """Remove issuebot-managed clones. Requires a selector (refs, --all, or
    --merged). Refuses dirty or unpushed clones unless --force. --merged uses
    `gh pr view` as the source of truth."""
    if not refs and not all_ and not merged:
        typer.echo("Specify a selector: task refs, --all, or --merged.", err=True)
        raise typer.Exit(1)

    connections, git = _connections()
    wanted = set(refs or [])
    removed = 0
    for p in connections:
        # Clones belong to connections whose working copy IS a clone, which
        # is what `repo` says — not to a strategy value any more.
        if not conn_setting(p, "repo"):
            continue
        for c in workspaces.list_clones(p, clone_root=git.clone_root):
            if refs and c.ref not in wanted:
                continue
            if merged and not workspaces.pr_merged(c.path, c.branch):
                continue
            if not force and (c.dirty or c.unpushed):
                typer.echo(f"skip {c.ref}: dirty/unpushed (use --force).", err=True)
                continue
            # A clone is a standalone repository; it needs no owning folder.
            ok = workspaces.remove(c, force=force)
            if ok:
                removed += 1
            typer.echo(f"{'removed' if ok else 'failed'} {c.ref} ({c.path})")
    if removed == 0:
        typer.echo("No matching clones to prune.")
